apiVersion: v1
kind: Service
metadata:
  name: javacontainer
  namespace: javacontainer
spec:
  type: LoadBalancer
  selector:
    app: javacontainer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000